name: issue-must-follow-template

on:
  schedule:
    - cron: "0 * * * *" # pick a cron here, this is every 1h
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: luanpotter/changes-requested@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # these are optional, if you want to configure:
          days-until-close: 5
          trigger-label: status/no-follow-template
          closing-comment: This issue was closed by the follow-template bot. Please follow the issue template to provide necessary info.
          dry-run: false